apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: catholicon-ingress
spec:
  rules:
    - host: my-server.10.0.0.12.xip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: catholicon-service
              servicePort: 80
          - path: /seasons
            backend:
              serviceName: catholicon-ms-seasons-service
              servicePort: 81
          - path: /leagues
            backend:
              serviceName: catholicon-ms-leagues-service
              servicePort: 82
          - path: /unconfirmedResults
            backend:
              serviceName: catholicon-ms-result-service
              servicePort: 83

