apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: catholicon-monolith
spec:
  selector:
    app: catholicon-monolith
  ports:
    - protocol: TCP
      port: 800
      targetPort: 8080
  type: ClusterIP
