apiVersion: apps/v1
kind: Deployment
metadata:
  name: catholicon-ms-matchcard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catholicon-ms-matchcard
      version: v1
  template:
    metadata:
      labels:
        app: catholicon-ms-matchcard
        version: v1
    spec:
      containers:
        - name: catholicon-ms-matchcard
          image: rdomloge/catholicon-ms-matchcard-armv7
          ports:
            - containerPort: 8080
