apiVersion: v1
kind: Service
metadata:
  name: catholicon-service
  namespace: catholicon
spec:
  selector:
    app: catholicon
  ports:
    - protocol: TCP
      port: 800
      targetPort: 8080
  type: ClusterIP
