apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: club
    namespace: catholicon
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: catholicon-ms-club
    minReplicas: 1
    maxReplicas: 3
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
