apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catholicon-ingress
  namespace: catholicon
  annotations: 
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
spec:
  rules:
    - host: my-server.10.0.0.12.xip.io
      http: &http_rules
        paths:
          - path: /function
            pathType: Prefix
            backend:
              service:
                name: function-bridge
                port: 
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: catholicon-service
                port: 
                  number: 800
          - path: /seasons
            pathType: Prefix
            backend:
              service:
                name: catholicon-ms-seasons-service
                port: 
                  number: 81
          - path: /leagues
            pathType: Prefix
            backend:
              service:
                name: catholicon-ms-leagues-service
                port: 
                  number: 82
          - path: /unconfirmedResults
            pathType: Prefix
            backend:
              service:
                name: catholicon-ms-matchcard-service
                port: 
                  number: 84
          - path: /fixtures
            pathType: Prefix
            backend:
              service:
                name: catholicon-ms-matchcard-service
                port: 
                  number: 84
          - path: /divisions
            pathType: Prefix
            backend:
              service:
                name: catholicon-ms-matchcard-service
                port: 
                  number: 84
          - path: /clubs
            pathType: Prefix
            backend:
              service:
                name: catholicon-ms-club-service
                port: 
                  number: 85
    - host: rdomloge.entrydns.org
      http: *http_rules
    - host: catholicon.uk
      http: *http_rules
    - host: localhost
      http: *http_rules
  tls:
    - hosts:
      - catholicon.uk
      - rdomloge.entrydns.org
      secretName: letsencrypt-cluster-issuer-key
