apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: matchcard
    namespace: catholicon
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: catholicon-ms-matchcard
    minReplicas: 1
    maxReplicas: 10
    behavior:
      scaleDown:
        policies:
          - type: Percent
            value: 5
            periodSeconds: 5
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
