apiVersion: apps/v1
kind: Deployment
metadata:
  name: catholicon-ms-matchcard
  namespace: catholicon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catholicon-ms-matchcard
      version: v1
  template:
    metadata:
      labels:
        app: catholicon-ms-matchcard
        version: v1
    spec:
      containers:
        - name: catholicon-ms-matchcard
          lifecycle: #this is here to allow the pod to drain before it is stopped, to avoid errors (spotted during load test)
            preStop:
              exec:
                command:
                - sleep
                - "5"
          image: rdomloge/catholicon-ms-matchcard-multiarch
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "1000m"
              memory: "800Mi"
            limits:
              cpu: "2000m"
              memory: "1000Mi"
          ports:
            - containerPort: 8080
          livenessProbe: #to know when to restart a container.
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 300
          readinessProbe: #to know when a container is ready to start accepting traffic
            httpGet:
              path: /fixtures/search/countBySeason?season=0
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          startupProbe: #to know when a container application has started. If such a probe is configured, it disables liveness and readiness checks until it succeeds
            exec:
              command:
              - grep
              - 'Started CatholiconMsMatchcardApplication'
              - logs/ms-matchcard.log
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 30
